In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
print(np.ndim(a)) # 배열의 차원수
print(a.shape)    # 배열의 형상, 기본 2차원
print(a.shape[0])

1
(4,)
4


In [6]:
b = np.array([[1,2], [3,4], [5,6]])
print(np.ndim(b))
print(b.shape)

2
(3, 2)


In [10]:
a = np.array([[1,2]
            , [3,4]])
b = np.array([[5,6]
            , [7,8]])
print(a.shape)
print(b.shape)
np.dot(a, b)

(2, 2)
(2, 2)


array([[19, 22],
       [43, 50]])

In [12]:
a = np.array([[1,2,3]
            , [3,4,5]])
b = np.array([[5,6]
            , [7,8]
            , [9,1]])
print(a.shape)
print(b.shape)
np.dot(a, b)

(2, 3)
(3, 2)


array([[46, 25],
       [88, 55]])

In [15]:
a = np.array([[1,1,1]
            , [2,2,2]
            , [3,3,3]])
b = np.array([1,1,1])
print(a.shape)
print(b.shape)
np.dot(a, b)

(3, 3)
(3,)


array([3, 6, 9])